### ISSUE TITLE
Performing a diff on versions of this file, shows the actual change implemented

### ISSUE THREAD

**Issue by moltar** [gmournos/quicksight-as-code#3]
OMG, this is amazing and clever!! Thanks for sharing that. This one paragraph changes so much for me you have no idea!

> The QS developer runs script [make-template-choice.sh](https://github.com/gmournos/quicksight-as-code/blob/main/scripts/manual/make-template-choice.sh) for this analysis, in order to create a template from the updated analysis and to download its definition. At this point, the file e.g. [template-defs/sales-template-def.json](https://github.com/gmournos/quicksight-as-code/blob/main/template-defs/sales-template-def.json) has changed to reflect the requirement. However, it is cumbersome to locate the actual change because a lot of internal ids of the template also changed. To circumvent this problem, we can instead use file [template-defs/review/sales-template-def.json](https://github.com/gmournos/quicksight-as-code/blob/main/template-defs/review/sales-template-def.json), which is also generated when we run script [make-template-choice.sh](https://github.com/gmournos/quicksight-as-code/blob/main/scripts/manual/make-template-choice.sh). This is a projection of the template definition, without these internal ids. Performing a diff on versions of this file, shows the actual change implemented, providing for full transparency and traceability to requirements.

**Comment by gmournos** [comment]
Thanks moltar for your kind comments.
It is also the main motivating reason for the approach. To provide visibility to the changes made and to make software development practices (code [peer] review, walkthrough, pull request ...) possible for QuickSight development.
